# Layer configuration for meta-evb-nuc980
BBPATH .= ":${LAYERDIR}"
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "evb-nuc980-layer"
BBFILE_PATTERN_evb-nuc980-layer := "^${LAYERDIR}/"
BBFILE_PRIORITY_evb-nuc980-layer = "7"

LAYERSERIES_COMPAT_evb-nuc980-layer = "wrynose"
LAYERDEPENDS_evb-nuc980-layer = "numaker-layer"
