# Layer configuration for meta-evb-ma35 (MA35D0 + MA35D05K unified)
BBPATH .= ":${LAYERDIR}"
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "evb-ma35-layer"
BBFILE_PATTERN_evb-ma35-layer := "^${LAYERDIR}/"
BBFILE_PRIORITY_evb-ma35-layer = "7"

LAYERSERIES_COMPAT_evb-ma35-layer = "wrynose"
LAYERDEPENDS_evb-ma35-layer = "numaker-layer meta-arm"
