# meta-numaker parent layer configuration
BBPATH .= ":${LAYERDIR}"

BBFILES += "${LAYERDIR}/recipes-*/*/*.bb ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "numaker-layer"
BBFILE_PATTERN_numaker-layer := "^${LAYERDIR}/"
BBFILE_PATTERN_IGNORE_EMPTY_numaker-layer = "1"
BBFILE_PRIORITY_numaker-layer = "6"

LAYERSERIES_COMPAT_numaker-layer = "wrynose"
