# Layer configuration for meta-evb-ma35d05k
BBPATH .= ":${LAYERDIR}"
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "evb-ma35d05k-layer"
BBFILE_PATTERN_evb-ma35d05k-layer := "^${LAYERDIR}/"
BBFILE_PRIORITY_evb-ma35d05k-layer = "7"

LAYERSERIES_COMPAT_evb-ma35d05k-layer = "wrynose"
LAYERDEPENDS_evb-ma35d05k-layer = "numaker-layer meta-arm"
