name: OpenBMC building

on:
  workflow_dispatch:
    inputs:
      git-address:
        description: 'git-address'
        required: true
        default: 'https://github.com/opennuvoton/openbmc.git'
      branches-tags:
        description: 'branches-tags'
        required: true
        default: 'numaker'
      machine:
        description: 'machine'
        required: true
        default: 'meta-evb-nuc980'
      target:
        description: 'target'
        required: true
        default: 'nuwriter-nuc980-pack'

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2

    #- name: Install packages
    #  run: |
        #sudo apt-get update
        #sudo apt-get upgrade
        #sudo apt-get install -y git gcc g++ make file wget gawk diffstat bzip2 cpio chrpath zstd lz4 bzip2

    - name: Bulid
      run: |
        sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0
        TEMPLATECONF=meta-numaker/${{github.event.inputs.machine}}/conf/templates/default source oe-init-build-env build-nuc980
        bitbake ${{github.event.inputs.target}} --runall=fetch
        bitbake ${{github.event.inputs.target}}

    - name: Upload OpenBMC Images
      uses: actions/upload-artifact@v4
      with:
        name: openbmc-${{ github.event.inputs.machine }}-${{ github.event.inputs.target }}
        path: build-nuc980/tmp/deploy/images/
        if-no-files-found: error
